# config/packages/nucleos_antispam.yaml

nucleos_antispam:
  # Twig mail filter
  twig:
    mail:
      css_class: 'custom_class'
      at_text:   [ '[AT]', '(AT)', '[ÄT]' ]
      dot_text:  [ '[DOT]', '(DOT)', '[.]' ]

  # Time protection
  time:
    min: 5
    max: 3600
    global: true # This will add antispam to all forms

  # Honeypot protection
  honeypot:
    field: 'email_address'
    class: 'hidden'
    global: false
    provider: 'nucleos_antispam.provider.session'